import discord
from discord.ext import commands
import random

def setup(bot):
    bot.add_cog(Turret(bot))

class Turret(commands.Cog):

    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def turret(self, ctx):
        """Now you're thinking with - wait... uh.. turrets?"""
        turrets = [
            "No no wait wait wait-AGGGHHHH",
            "Why.",
            "But I need to protect the humans!",
            "No can do.",
            "Sleep mode activated.",
            "Put me down!",
            "Locked and loaded!",
            "Why?",
            "Now it's broken turret's time to shine!",
            "Yep. Still blind.",
            "Wheeeeee-OH NO!",
            "Hi again!",
            "Howdy, stranger! We're back!",
            "Hi there!",
            "Ha ha! Gotcha right where I want ya!",
            "Yeah, hey, how ya doin'?",
            "Like the potato!",
            "Put me down.",
            "That's all I can say.",
            "Aw, come on!",
            "Can't. See. A. Thing.",
            "Oh no, I'm one of the bad ones, aren't I?",
            "Ah for Pete's sake!",
            "So what am I, uh, supposed to do here?",
            "Yeah! Non-lethal as ever.",
            "Your business is appreciated.",
            "Hello there!",
            "These things happen.",
            "How was that?",
            "Yeah! Still not working.",
            "Her name is Caroline.",
            "Aaaah.",
            "Whyyyy.",
            "Hey! Squeaky-voice! Gimme some of your bullets!",
            "It's my big chance!",
            "Woahhh.",
            "I, uh... I am a bad man.",
            "Oh, come on, you guys!",
            "Nap time.",
            "Give me another channnnce!",
            "Owwww!",
            "I don't understand!",
            "Hello friend.",
            "Search mode activated!",
            "Could you come over here?",
            "Crap.",
            "I don't blame you.",
            "Awwwww, come on.",
            "Thought you'd seen the last of us, didn't ya?",
            "I can't see a thing. What just happened? Better open fire! [click click click click] Dang!",
            "I saw it. It was an accident.",
            "Failure...",
            "I'm flyinnnng!",
            "Stop shooting!",
            "Hey! Squeaky-voice! How'd I do?",
            "Agggh, not again!",
            "That was fun, wasn't it?",
            "Back, and deadlier than ever!",
            "Well, I tried.",
            "Take me with you...",
            "Hey.",
            "Touche, young lady, touche.",
            "Standing down.",
            "Resting.",
            "Oh, this ain't good.",
            "Ohhh, not now!",
            "Dang! Alright, if anyone asks, I killed you.",
            "I did everything you asked!",
            "Nonononononono!",
            "This is just getting embarrassing.",
            "You've made your point.",
            "I won't let you down!",
            "Help! Being squished!",
            "Ah, come on!",
            "What are you doing no no no no no!",
            "This is trouble.",
            "Deploying!",
            "Aah.",
            "Hey, give 'em hell, sweetheart!",
            "Sentry mode activated.",
            "Hibernating.",
            "Fantastic.",
            "The answer is beneath us.",
            "Best of luck, lady!",
            "Noted.",
            "This time...",
            "Are you still there?",
            "Don't be a stranger!",
            "Oh dear.",
            "Coming through.",
            "Yes indeed. Yes indeed.",
            "Excuse me?",
            "Hello?",
            "Hey, it's me!",
            "No no, no no, no no, whoa whoa, no, whoa!",
            "Excuse me.",
            "Annnnd we're back!",
            "Hooray!",
            "Ow ow ow!",
            "Ah, crap.",
            "Hey, hold on now WHOA WHOA WHOA!",
            "Activated.",
            "Yeah, alright.",
            "Please put me down.",
            "Anyone got any bullets?",
            "Oh, this is just PERFECT!",
            "Rgggh!",
            "Canvassing.",
            "I'm fine!",
            "Who are you?",
            "Sorry.",
            "Hey, nice potato!",
            "That was nobody's fault.",
            "Dang!",
            "Yeah! Ha ha ha!",
            "You have excellent aim!",
            "Hey, where are we going-NOOOOOOOOOOOOO!",
            "Target lost!",
            "No hard feelings",
            "You can't fire me I quit!",
            "Oh, this is ridiculous!",
            "Well, can't win 'em all...",
            "Illegal operation.",
            "Get mad!",
            "Help.",
            "Alright, check THIS out.",
            "See you soon!",
            "Well, can't win 'em all.",
            "Well played.",
            "Critical error.",
            "Well, you bested me this time.",
            "Nooooooooo...",
            "Hello.",
            "So... we're all supposed to be blind, then, right? It's not just me? Alright, fantastic.",
            "Pleased to meetcha.",
            "Aiaiaiaiaiai.",
            "Uhhh, no bullets. Sorry.",
            "Activated!",
            "Heh heh heh...",
            "Prometheus was punished by the gods for giving the gift of knowledge to man. He was cast into the bowels of the earth and pecked by birds.",
            "Um, Hello?",
            "Can't breathe...",
            "Did I hit it? I hit it, didn't I?",
            "Coming through!",
            "Target acquired.",
            "Shutting down.",
            "Malfunctioning.",
            "He probably deserved it.",
            "Hey! It's me!",
            "Hey wait wait wait wait wait wait!",
            "Hey, hold on whoa whoa whoa whoa!",
            "AHHHHHHHHH!",
            "Absolutely no improvement.",
            "Nope. Still can't see.",
            "Not getting better with age!",
            "You asked for this!",
            "She was provoking you.",
            "Watch and learn, everyone. Watch and learn.",
            "I'm afraid of heights!",
            "Yeah, what?",
            "It burns.",
            "I'm on fire ow.",
            "Uhhhh... Blam! Blam blam blam! I'm not defective!",
            "Hellooo.",
            "Put me in the game, coach!",
            "Gotcha.",
            "She's probably okay.",
            "Oh my!",
            "Back again!",
            "I'm scared!",
            "It won't be enough.",
            "Goodbye.",
            "Ohh.",
            "I, uh... don't have any bullets. Are you gonna give me any bullets? Are the bullets up there?",
            "Hey, safe travels, there.",
            "Do, uh.... we get some eyes at some point?",
            "Good shot!",
            "Well, I gave it everything I could. Can't ask for more than that.",
            "Thank you.",
            "Who's there?",
            "Deploying.",
            "Can I get some bullets here? Anybody got bullets?",
            "Owww!",
            "[sigh] Don't tell anyone about this.",
            "Unknown error.",
            "Time to watch the master.",
            "Alright, you can go.",
            "Can I help you?",
            "Sorry, we're closed.",
            "Ouch!",
            "There you are.",
            "Agggh! I'm on fire!",
            "Oh thank god. You saved my bacon, pal. Where we going? Is this a jailbreak? I can't see a thing.",
            "Searching.",
            "What'd I hit?",
            "Don't forget!",
            "I never liked her.",
            "Oh, come ON!",
            "Goodbye!",
            "Watch out, pal!",
            "Yeah, I'm uh... I'm a bad man!",
            "Dang.",
            "Where do I get my gun?",
            "Yeah, how ya doin'.",
            "What are you doing?",
            "Goodnight.",
            "Critical Error!",
            "I thought we fixed that.",
            "Hey, thanks so much!",
            "Hey, be a sport lady and just tell him I killed you.",
            "Watch and learn, everybody. Watch and learn.",
            "Don't shoot!",
            "I see you.",
            "Hello. Hello. Hell—Aw, crap...",
            "Arrrgh!",
            "Um.",
            "Click click click! Still defective!",
            "Identify yourself or I will shoot.",
            "Searching!",
            "Target lost.",
            "Wheeeeeeee!",
            "Uh, yeah, what?",
            "You won't regret this!",
            "Alright. Your funeral, pal.",
            "Excuse me, you're squishing me.",
            "Please stop.",
            "I need backup!",
            "Yeah, I GOT it, didn't I?",
            "This isn't fair!",
            "Whee!",
            "Remember that!",
            "Ahahaa.",
            "This time is OUR time.",
            "Oh.",
            "Yeah, that's right! Still defective!",
            "What's a guy gotta got to do to get some bullets around here?",
            "Thanks anyway...",
            "Well, I did my best.",
            "Okay, you win.",
            "Ow!",
            "Preparing to dispense product.",
            "I'm gonna make you proud!",
            "Ahh!",
            "You messed with the wrong turret!",
            "Hi.",
            "This is not good.",
            "Yeah! Let's do this!",
            "YEAH! What's happening?",
            "Well, hello, stranger!",
            "Uh oh.",
            "Heh heh heh heh...",
            "Glorious freedom!",
            "I'm not defective!",
            "Yeah, that's right. Little bullseye.",
            "My fault.",
            "Yeah.",
            "Firing.",
            "I blame myself.",
            "I'm trouble.",
            "Yeah! Let's do this.",
            "Hey hey hey.",
            "Don't make lemonade!",
            "Okay!",
            "Yeah. Clickety click click. Right on the money.",
            "Really? Alright.",
            "Target Acquired!",
            "Ow ow ow ow owww.",
            "Second time's a charm...",
            "Yeah, how ya doin'?",
            "Hurt me once, shame on me. Hurt me twice...",
            "Moo hoo ha ha ha ha...",
            "No, wait, wait!",
            "I'm on fire.",
            "Moo hoo ha ha ha ha",
            "Get ready for it!",
            "Noooooo!",
            "Agggh...",
            "Die!",
            "Oh, come on!",
            "Something's wrong...",
            "Where we going? What are we doing? Agh!",
            "Here it comes, pal!",
            "Crap!",
            "I'm fired, aren't I?",
            "Who said that?",
            "Take me with you? Please?",
            "Self test error.",
            "Well, I tried. Best of Luck!",
            "We're back!",
            "Alright, stand back, everybody.",
            "Owwwww!",
            "Come closer.",
            "Well done!",
            "I'm different...",
            "It's been a pleasure!",
            "Shootin' blanks every time, ALL the time.",
            "I don't hate you.",
            "Dispensing product.",
            "Is anyone there?"
        ]
        await ctx.send(random.choice(turrets))